// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqcgd3cVVh0CxEIKuTN_cKk-j8HxMPO38',
    appId: '1:755366709835:web:741332af83fc0f47e51bce',
    messagingSenderId: '755366709835',
    projectId: 'spotify-cd009',
    authDomain: 'spotify-cd009.firebaseapp.com',
    storageBucket: 'spotify-cd009.appspot.com',
    measurementId: 'G-54V69W63EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZi3Nlmcnl7jcqzawQenwZI35yFRycbnY',
    appId: '1:755366709835:android:2691bb9aa94c04dde51bce',
    messagingSenderId: '755366709835',
    projectId: 'spotify-cd009',
    storageBucket: 'spotify-cd009.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyZKR6d58vJ9DX2sHcFHPgmHD4bCEiIRY',
    appId: '1:755366709835:ios:8e84473c69e61ee9e51bce',
    messagingSenderId: '755366709835',
    projectId: 'spotify-cd009',
    storageBucket: 'spotify-cd009.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyZKR6d58vJ9DX2sHcFHPgmHD4bCEiIRY',
    appId: '1:755366709835:ios:8e84473c69e61ee9e51bce',
    messagingSenderId: '755366709835',
    projectId: 'spotify-cd009',
    storageBucket: 'spotify-cd009.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqcgd3cVVh0CxEIKuTN_cKk-j8HxMPO38',
    appId: '1:755366709835:web:ccdcdf2e4c13bd22e51bce',
    messagingSenderId: '755366709835',
    projectId: 'spotify-cd009',
    authDomain: 'spotify-cd009.firebaseapp.com',
    storageBucket: 'spotify-cd009.appspot.com',
    measurementId: 'G-MY9T91XEJ4',
  );
}
